# Generated by Django 5.1.8 on 2025-06-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_type'),
        ('payments', '0002_remove_payment_order_payment_metadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
            preserve_default=False,
        ),
    ]
