# Generated by Django 5.1.8 on 2025-05-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cart_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
