# Generated by Django 5.1.8 on 2025-05-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_cart_created_at_remove_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
