# Generated by Django 5.1.8 on 2025-05-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_cartitem_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
