# Generated by Django 5.1.8 on 2025-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_cart_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10),
        ),
    ]
