# Generated by Django 5.1.8 on 2025-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment')], default='order', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='message',
            field=models.TextField(),
        ),
    ]
