# Generated by Django 5.1.8 on 2025-06-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_type'),
        ('payments', '0002_remove_payment_order_payment_metadata_and_more'),
        ('user_staff', '0002_staffnotification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.payment'),
        ),
    ]
