# Generated by Django 5.1.8 on 2025-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0003_staffnotification_order_staffnotification_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
