# Generated by Django 5.1.8 on 2025-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0004_staffnotification_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
