# Generated by Django 5.1.8 on 2025-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0006_notification_delete_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
