# Generated by Django 5.1.8 on 2025-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_staff', '0007_notification_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('order_Status', 'order_Status'), ('payment', 'Payment'), ('feedback', 'Feedback'), ('user_registration', 'User Registration')], default='order', max_length=30),
        ),
    ]
