# Generated by Django 5.1.8 on 2025-06-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='current_order',
        ),
    ]
