# Generated by Django 5.1.8 on 2025-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('VIP', 'VIP Items'), ('NORMAL', 'Normal Items'), ('COMMON', 'Common Items')], default='NORMAL', help_text='VIP items are only available in VIP rooms', max_length=10),
        ),
    ]
