# Generated by Django 5.1.8 on 2025-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('VIP', 'VIP Items'), ('NORMAL', 'Normal Items')], default='NORMAL', help_text='VIP items are only available in VIP rooms', max_length=10),
        ),
    ]
