# Generated by Django 5.1.8 on 2025-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='NORMAL', help_text='VIP items are only available in VIP rooms', max_length=10),
        ),
    ]
