# Generated by Django 5.1.8 on 2025-05-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_type'),
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Average preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular Item'), ('VIP_ONLY', 'VIP Exclusive'), ('VIP_PRIORITY', 'VIP Priority')], default='REGULAR', help_text='VIP designation for this menu item', max_length=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_items/'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available'], name='menuitems_m_is_avai_935350_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['vip_status'], name='menuitems_m_vip_sta_207ab1_idx'),
        ),
    ]
