# Generated by Django 5.1.8 on 2025-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_menuitem_preparation_time_menuitem_vip_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular Item'), ('VIP_ONLY', 'VIP Exclusive'), ('VIP_PRIORITY', 'VIP Priority')], default='REGULAR', help_text='Automatically set based on category type (VIP/NORMAL)', max_length=12),
        ),
    ]
