# Generated by Django 5.1.8 on 2025-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0003_alter_menuitem_vip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular Item'), ('VIP_ONLY', 'VIP Exclusive'), ('VIP_PRIORITY', 'VIP Priority')], default='REGULAR', help_text='Choose the item type regardless of category', max_length=12),
        ),
    ]
