# Generated by Django 5.1.8 on 2025-05-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_category_type'),
        ('menuitems', '0005_category_alter_menuitem_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular Item'), ('VIP_ONLY', 'VIP Exclusive')], default='REGULAR', help_text='Choose the item type regardless of category', max_length=12),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
