# Generated by Django 5.1.8 on 2025-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0009_alter_menuitem_vip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='vip_status',
            field=models.CharField(choices=[('REGULAR', 'Regular Item'), ('VIP_ONLY', 'VIP Exclusive'), ('TODAYS_SPECIAL', "Today's Special")], default='REGULAR', help_text='Manually set  (VIP/NORMAL)', max_length=25),
        ),
    ]
