# Generated by Django 5.1.8 on 2025-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rush',
            field=models.BooleanField(default=False),
        ),
    ]
