# Generated by Django 5.1.8 on 2025-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_rush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
